# Generated by Django 4.0.2 on 2022-02-19 12:02

import datawork.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
                ('category_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_owner', models.CharField(max_length=300)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_color', models.CharField(max_length=200)),
                ('vehicle_image', models.ImageField(upload_to='images/vehicle/')),
                ('owner_image', models.ImageField(upload_to='images/owner/')),
                ('vehicle_token', models.IntegerField(default=datawork.models.random_token)),
                ('vehicle_arrival', models.DateTimeField(auto_now_add=True)),
                ('vehicle_departure', models.DateTimeField()),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.category')),
            ],
        ),
    ]
