# Generated by Django 4.0.2 on 2022-02-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
